# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFiles',
            fields=[
                ('unique_file_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('absolut_file_path', models.CharField(db_index=True, max_length=500, unique=True)),
                ('original_file_name', models.CharField(max_length=500)),
                ('upload_into_es_task_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('upload_into_es_rows_count', models.PositiveIntegerField(null=True)),
                ('upload_into_es_cols_count', models.PositiveIntegerField(null=True)),
                ('upload_into_es_file_size', models.PositiveIntegerField(null=True)),
                ('upload_into_es_settings_rcs', models.PositiveSmallIntegerField(null=True)),
                ('upload_into_es_settings_pp', models.PositiveSmallIntegerField(null=True)),
                ('upload_into_es_settings_ics', models.PositiveSmallIntegerField(null=True)),
                ('upload_into_es_tm', models.PositiveIntegerField(null=True)),
            ],
            options={
                'db_table': 'uploaded_files',
            },
        ),
    ]
