# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfiles',
            old_name='upload_into_es_tm',
            new_name='upload_into_es_itm',
        ),
        migrations.AddField(
            model_name='uploadedfiles',
            name='upload_into_es_ttm',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
