# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170717_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfiles',
            name='upload_into_es_itm',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='uploadedfiles',
            name='upload_into_es_ttm',
            field=models.FloatField(null=True),
        ),
    ]
