# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170718_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfiles',
            name='file_upload_date_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='uploadedfiles',
            name='upload_into_es_indexing_done',
            field=models.DateTimeField(),
        ),
    ]
